apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "12345887"
  annotations:
    github.com/project-slug: ibrt2016/terraform-azure-web-mybob420 # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://github.com/claranet/terraform-azurerm-vnet
    title: 'VNet Terraform Module'
    icon: github
  tags:
    - azure
    - vnet
    - brand-new-deployment
    - high-criticality
    - ticket-number-12345887
    - entity-jp
    - owner-bob---------tayara
    - mybob420
    - prod
    - created-on-2024-07-28
  title: 'Brand new Azure Reource Group and Virtal Network - Ticket #12345887' # you can give any title
  description: |
   Create brand new Azure Reource Group and Virtal Network in stack `mybob420` in `prod` environment\
   \
   **Ticket number:**  12345887\
   **Created on:**  2024-07-28\
   Details: Create Azure Virtual network and a resource group in a brand new stack mybob420, in prod environment and in us-east region\
   Action: Create a new Resource Group and a new Virtual Network`\
   Brand new deployment: Yes\
   Azure region: us-east\
   VNet address space: 10.3.0.0/16\
   VNet suffix: 001\
   Stack name: mybob420\
   Stack owner: Bob         Tayara\
   Azure subscription: web\
   Criticality: High\
   Entity: JP\
   Cost center: 00034
spec:
  type: service
  owner: user:guest
  lifecycle: experimental